# By yushi4ka
# v1.1.0

# Download: PlaceholderAPI and LuckPerms
# For PlaceholderAPI: /papi ecloud download LuckPerms
# Colors: Â§ and &
# Plugin Placeholders: %name% and %killer%

Messages:
  tag: "&f[&#E43A96S&#E5489Da&#E756A4k&#E864ACu&#EA72B3r&#EB80BAa&#EC8EC1H&#EE9CC8e&#EFAAD0a&#F1B8D7d&#F2C6DEs&f] "
  no-permission: "Â§cÂ§lÃ— Â§cĞ£Ğ²Ğ°Ñ Ğ½Ğµ Ğ´Ğ¾ÑÑ‚Ğ°Ñ‚Ğ¾Ñ‡Ğ½Ğ¾ Ğ¿Ñ€Ğ°Ğ²!"
  cmd-reload-message: "Â§aÂ§lâœ… Â§aĞŸĞ»Ğ°Ğ³Ğ¸Ğ½ Ğ±Ñ‹Ğ» Ğ¿ĞµÑ€ĞµĞ·Ğ°Ğ³Ñ€ÑƒĞ¶ĞµĞ½!"
  death-message: "Â§cÂ§lğŸ’€ Â§r%name% Â§cĞ’Ñ‹ ÑƒĞ¼ĞµÑ€Ğ»Ğ¸ Ğ¸ Ğ¿Ğ¾Ñ‚ĞµÑ€ÑĞ»Ğ¸ Ğ³Ğ¾Ğ»Ğ¾Ğ²Ñƒ."
  killer-message: "Â§cĞ£Ğ±Ğ¸Ğ¹Ñ†Ğ°: Â§f%killer%"
